import { FlowSubscription } from './flowSubscription.model';
import { FlowOrder } from './flowOrder.model';
import { CreditCard } from './creditCard.model';
import { OgoneAuthorisation } from './ogoneAuthorisation.model';
export interface FlowState {
  IsEditable?: boolean;
  ActiveStepId?: number;
  Module?: string;
  CategoryID?: number;
  CategoryLabel?: string;
  DurationID?: string;
  DurationTime?: number;
  DurationUnit?: string;
  ReservationID?: number;
  CAClientID?: number;
  Client?: string;
  EventID?: number;
  FirstName?: string;
  LastName?: string;
  Email?: string;
  Company?: string;
  Address?: string;
  Postalcode?: string;
  City?: string;
  Country?: string;
  GuestName?: string;
  GuestEmail?: string;
  ReserveForOther?: boolean;
  SubscriptionName?: string;
  InternalRemark?: string;
  Remark?: string;
  OnlineRes?: boolean;
  Passage?: boolean;
  StatusID?: number;
  WaitingListPosition?: number;
  Subscription?: FlowSubscription;
  ReservationOrder?: FlowOrder;
  AdvanceIsPercentage?: boolean;
  AdvancePercentage?: number;
  MinimumAdvance?: number;
  Parking?: number;
  Phone?: string;
  IsLastMinute?: boolean;
  LastMinuteError?: boolean;
  LastMinuteErrorMessage?: string;
  ArrivalTime?: string;
  DepartureDateTime?: string;
  ArrivalDateTime?: string;
  ArrivalDate?: string;
  Guid?: string;
  NOPersons?: number;
  NOPersons1?: number;
  NOPersons2?: number;
  NOPersons3?: number;
  NOPersons4?: number;
  TotalNOPersons?: number;
  OfferID?: number;
  OfferDescription?: string;
  PictureLink?: string;
  PictureLinkLarge?: string;
  OfferLegalDescription?: string;
  FlowID?: number;
  ModifiedComments?: boolean;
  Modified?: boolean;
  EventLabel?: string;
  ClientID?: number;
  SubClientID?: number;
  RN_PartnerID?: number;
  ApplicationID?: number;
  FreeBitField1?: boolean;
  FreeBitField2?: boolean;
  FreeBitField3?: boolean;
  FreeBitField4?: boolean;
  NewsLetter?: boolean;
  EnteredPinCode?: number;
  FriendlyName?: string;
  LoggedIn?: boolean;
  AcceptedTerms?: boolean;
  AcceptedPrivacyConditions?: boolean;
  PriceMatrixID?: number;
  BirthDay?: string;
  TimeoutTime?: string;
  TimeslotID?: number;
  ResourceID?: string;
  AreaID?: number;
  ReservationCost?: string;
  Creditcard?: CreditCard;
  OgoneAuthorisation?: OgoneAuthorisation;
  PersonID?: number;
  FreeIntegerField1?: number;
  FreeIntegerField2?: number;
  FreeIntegerField3?: number;
  FreeIntegerField4?: number;
  FreeReferenceID1?: number;
  FreeReferenceID2?: number;
  FreeReferenceID3?: number;
  FreeReferenceID4?: number;
  FreeTextField1?: string;
  FreeTextField2?: string;
  FreeTextField3?: string;
  FreeTextField4?: string;
  AllergiesIncluded?: boolean;
  TitleID?: number;
  MemberID?: number;
  FlowResultGuid?: string;
  TopMessage?: string;
  MiddleMessage?: string;
  HourSelectionMessage?: string;
  PersonProperties?: any;
  CreditCardAliases?: any;
  VoucherData?: any;
  SkipTableAssign?: boolean;
  ReservationMode?: string;
  PaymentType?: any;
  AutoAssign?: boolean;
  Reference?: string;
  Mobile?: string;
  VoucherTypeID?: number;
  VoucherID?: number;
  VerificationCode?: string;
  SMS_Voucher?: string;
  OF_OfferID?: number;
  NOParkings?: number;
  Telephone?: string;
  ContactPerson?: any;
  GaClientID(string, optional);
  /*         Dixys.Dto.PF.FlowSubscription {}
        Dixys.Dto.PF.FlowOrder {}
        Dixys.Dto.PF.PhoneNumber {}
        Dixys.Dto.PF.ReservationCost {}
        Dixys.Dto.PF.Creditcard {}
        Dixys.Dto.PF.OgoneAuthorisation {}
        Dixys.Dto.PL.PersonPropertyCollection {}
        Dixys.Dto.FI.CreditCardAlias {}
        Dixys.Dto.FI.VoucherData {}
        Dixys.Dto.FI.PaymentType {}
        Dixys.Dto.PF.ReservationContact {}
 */
}
